"""Verify Shantae writable-code writers against the stock ROM, without gameplay.

This is a reproducible inventory of identified RAM programs, not a formal proof
that arbitrary control flow cannot execute other writable bytes.
"""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROM = (ROOT / "roms/shantae.gbc").read_bytes()
WRITERS = [
    (1, 0x41A3, "VBlank vector C374 and data pointer C372", "3e 12 ea 72 c3 3e c3 ea 73 c3 3e c3 ea 74 c3 3e 43 ea 75 c3 3e 0a ea 76 c3 c9"),
    (0, 0x0B6E, "text opcode vector C385", "3e c3 ea 85 c3"),
    (0, 0x2730, "graphics vector FFA1", "3e c3 e0 a1"),
    (1, 0x4748, "text vector FFA3 -> 0B9D", "3e c3 e0 a3 3e 9d e0 a4 3e 0b e0 a5"),
    (1, 0x47F6, "text vector FFA3 -> 0BBA", "3e c3 e0 a3 3e ba e0 a4 3e 0b e0 a5"),
    (1, 0x4CB6, "32 objects, WRAM3:D000, stride 7E, JP fields 1A and 29",
     "f0 70 f5 3e 03 e0 70 3e 03 e0 70 01 c0 0f 21 00 d0 af 22 0b 79 b0 20 f9 01 00 d0 3e 20 f5 21 00 00 09 3e ff 77 21 1a 00 09 3e c3 22 21 29 00 09 3e c3 22 21 7c 00 09 79 c6 7e 22 4f 78 ce 00 32 47 f1 3d 20 d8"),
    (1, 0x7120, "12 records, WRAM7:DD40, stride 13, JP fields 2/5/8/B",
     "f0 70 f5 3e 07 e0 70 01 40 dd 3e 0c f5 21 00 00 09 af 77 21 02 00 09 3e c3 22 3e 41 22 3e 0c 22 21 05 00 09 3e c3 22 3e 41 22 3e 0c 22 21 08 00 09 3e c3 22 3e 41 22 3e 0c 22 21 0b 00 09 3e c3 22 3e 41 22 3e 0c 22 21 10 00 09 79 c6 13 22 4f 78 ce 00 32 47 f1 3d 20 b3"),
    (1, 0x7CFC, "10-byte DMA program copied from 01:7D0A to FF80",
     "0e 80 06 0a 21 0a 7d 2a e2 0c 05 20 fa c9 3e c0 e0 46 3e 28 3d 20 fd c9"),
]


def main():
    assert hashlib.sha256(ROM).hexdigest() == "1b92e22d5510c51bab97d23074e4aad7464d93eb15f7596ef7da0a5efa27a19d"
    writers = []
    for bank, address, description, hex_bytes in WRITERS:
        expected = bytes.fromhex(hex_bytes)
        offset = bank * 0x4000 + address % 0x4000
        assert ROM[offset:offset + len(expected)] == expected, f"Writer changed: {bank:02X}:{address:04X}"
        writers.append(dict(bank=bank, address=f"{address:04X}", description=description, bytes=hex_bytes))

    # Whole-ROM scan, not the heuristic code-bank list. Classify every immediate
    # C3 load immediately stored to memory, including two non-code uses.
    expected_sites = {0x0B6E, 0x2730, 0x41A8, 0x41AD, 0x4748, 0x47F6,
                      0x4CDF, 0x4CE6, 0x7137, 0x7144, 0x7151, 0x715E, 0x300A4}
    found = set()
    for offset in range(len(ROM) - 3):
        if ROM[offset:offset + 2] == b"\x3e\xc3" and ROM[offset + 2] in (0xEA, 0xE0, 0x22, 0x77, 0x12, 0x02, 0xE2):
            found.add(offset)
    assert found == expected_sites, f"C3 writer inventory changed: {found ^ expected_sites}"
    slots = [(0, a) for a in (0xC374, 0xC385, 0xFFA1, 0xFFA3)]
    slots += [(3, 0xD000 + n * 0x7E + off) for n in range(32) for off in (0x1A, 0x29)]
    slots += [(7, 0xDD40 + n * 0x13 + off) for n in range(12) for off in (2, 5, 8, 11)]
    assert len(slots) == 116
    listing = ["; Shantae writable-code inventory, generated by tools/audit_ram_coverage.py",
               "; nn is a live patched destination; byte operands are not baked into native code."]
    for bank, addr in slots:
        region = f"WRAM{bank}" if addr < 0xFF80 else "HRAM"
        listing.append(f"{region}:{addr:04X}  C3 ?? ??  JP nn")
    listing += ["HRAM:FF80  3E ??     LD A,page", "HRAM:FF82  E0 46     LDH ($46),A",
                "HRAM:FF84  3E ??     LD A,count", "HRAM:FF86  3D        DEC A",
                "HRAM:FF87  20 FD     JR NZ,$FF86", "HRAM:FF89  C9        RET"]
    (ROOT / "generated/shantae_ram.asm").write_text("\n".join(listing) + "\n")
    source = (ROOT / "generated/shantae.c").read_text()
    for forbidden in ("gbrt_try_execute_hram_stub(", "gbrt_try_execute_ram_stub(", "gbrt_try_execute_highmem_stub("):
        assert forbidden not in source, f"Generic RAM decoder remains in production dispatch: {forbidden}"
    report = {
        "scope": "Identified writable programs and their ROM writers; no gameplay-derived entry list",
        "formal_reachability_proof": False,
        "writers": writers,
        "immediate_C3_store_candidates_all_256_banks": len(found),
        "non_code_C3_stores": {"01:41A8": "high byte of data pointer C372", "0C:40A4": "low byte of object callback target 40C3"},
        "jp_slots": [{"wram_bank": bank, "address": f"{addr:04X}", "instruction": "JP live_u16"} for bank, addr in slots],
        "dma_entries": [f"FF{x:02X}" for x in (0x80, 0x82, 0x84, 0x86, 0x87, 0x89)],
        "generic_ram_opcode_helpers_in_production": False,
        "unknown_writable_code": "fatal diagnostic; not counted as covered",
    }
    path = ROOT / "logs/ram-coverage.json"
    path.parent.mkdir(exist_ok=True)
    path.write_text(json.dumps(report, indent=2) + "\n")
    print(f"PASS: {len(writers)} verified ROM writer regions, {len(found)} classified C3 stores, {len(slots)} JP slots, 6 DMA entries")
    print("Scope: identified RAM programs; not a formal proof of all writable-memory reachability.")


if __name__ == "__main__":
    main()
